# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 01:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maSo', models.CharField(max_length=20, unique=True)),
                ('tenVo', models.CharField(max_length=30)),
                ('tenChong', models.CharField(max_length=30)),
                ('nsVo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1950)])),
                ('nsChong', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(1950)])),
                ('lienHe', models.CharField(max_length=30)),
            ],
        ),
    ]
