# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trung',
            fields=[
                ('tt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quanly.ThongTin')),
                ('GV', models.IntegerField(default=0)),
                ('MI', models.IntegerField(default=0)),
            ],
        ),
    ]
