# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_trung'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=10)),
                ('nghiHuu', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='thongtin',
            name='bs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.BacSi'),
        ),
    ]
