# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_auto_20170320_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='trung',
            name='col',
            field=models.CharField(default=b'#ffffff', max_length=8),
        ),
    ]
