# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0005_auto_20170322_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trung',
            name='col',
            field=models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], default=b'#000000', max_length=8),
        ),
    ]
