# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0006_auto_20170323_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phoi',
            fields=[
                ('tt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quanly.ThongTin')),
                ('loai1', models.IntegerField(default=0)),
                ('loai2', models.IntegerField(default=0)),
                ('loai3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TruPhoi',
            fields=[
                ('tt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quanly.ThongTin')),
                ('maDongPhoi', models.CharField(max_length=20, unique=True)),
                ('label00', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label01', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label02', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label03', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label10', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label11', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label12', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label13', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label20', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label21', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label22', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
                ('label23', models.CharField(choices=[(b'#ff0000', b'\xc4\x90\xe1\xbb\x8f'), (b'#00ff00', b'Xanh l\xc3\xa1'), (b'#0000ff', b'Xanh d\xc6\xb0\xc6\xa1ng'), (b'#ffff00', b'V\xc3\xa0ng'), (b'#fcfbe3', b'Kem'), (b'#ffffff', b'Tr\xe1\xba\xafng'), (b'#ffa500', b'Cam'), (b'rgba(0, 0, 0, 0)', b'\xc4\x90\xc3\xa3 chuy\xe1\xbb\x83n')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='trung',
            name='col',
        ),
    ]
