# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0012_auto_20170325_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtin',
            name='bs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.BacSi'),
        ),
        migrations.AlterField(
            model_name='thongtin',
            name='lienHe',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
