# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0016_kythuatvien_testtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='truphoi',
            name='loai00',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai01',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai02',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai03',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai10',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai11',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai12',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai13',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai20',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai21',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai22',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai23',
            field=models.CharField(choices=[(b'0', b'------'), (b'1', b'Lo\xe1\xba\xa1i 1'), (b'2', b'Lo\xe1\xba\xa1i 2'), (b'3', b'Lo\xe1\xba\xa1i 3')], default=b'0', max_length=1),
        ),
    ]
