# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 08:19
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0018_auto_20170402_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocHut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HCG', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('gioCH', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('soNang', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])),
                ('added', models.BooleanField(default=False)),
                ('tt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quanly.ThongTin')),
            ],
        ),
    ]
