# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0019_chochut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truphoi',
            name='loai00',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai01',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai02',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai03',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai10',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai11',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai12',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai13',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai20',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai21',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai22',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai23',
            field=models.CharField(choices=[(b'l0', b'------'), (b'l1', b'Lo\xe1\xba\xa1i 1'), (b'l2', b'Lo\xe1\xba\xa1i 2'), (b'l3', b'Lo\xe1\xba\xa1i 3')], default=b'l0', max_length=2),
        ),
    ]
