# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0020_auto_20170409_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kythuatvien',
            name='testTime',
        ),
        migrations.AlterField(
            model_name='chochut',
            name='HCG',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2010, 1, 1, 0, 0)),
        ),
    ]
