# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0021_auto_20170409_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chochut',
            name='gioCH',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2010, 1, 1, 0, 0)),
        ),
    ]
