# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0023_auto_20170409_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truphoi',
            name='loai01',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai02',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai03',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai11',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai12',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai13',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai21',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai22',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai23',
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai00',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai20',
            field=models.IntegerField(default=0),
        ),
    ]
