# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0024_auto_20170416_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truphoi',
            name='label00',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label01',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label02',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label03',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label10',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label11',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label12',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label13',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label20',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label21',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label22',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='label23',
            field=models.CharField(default=b'rgba(0, 0, 0, 0)', max_length=20),
        ),
    ]
