# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0025_auto_20170416_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truphoi',
            name='loai00',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai10',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai20',
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai001',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai002',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai003',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai101',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai102',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai103',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai201',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai202',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truphoi',
            name='loai203',
            field=models.IntegerField(default=0),
        ),
    ]
