# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 10:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0026_auto_20170416_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenPhoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soPhoiRa', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ngayKiemTra', models.DateField(blank=True, default=datetime.datetime.now)),
                ('ngayChuyenPhoi', models.DateField(blank=True, default=datetime.datetime.now)),
                ('added', models.BooleanField(default=False)),
                ('tt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quanly.ThongTin')),
            ],
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai001',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai002',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai003',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai101',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai102',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai103',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai201',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai202',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='truphoi',
            name='loai203',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
