# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0028_dongphoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='chochut',
            name='stt',
            field=models.IntegerField(default=0),
        ),
    ]
