# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0031_auto_20170424_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truphoi',
            name='loai001',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai002',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai003',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai101',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai102',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai103',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai201',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai202',
        ),
        migrations.RemoveField(
            model_name='truphoi',
            name='loai203',
        ),
    ]
